 "use client";
import Link from "next/link";
import { useEffect, useState } from "react";
const modules = [["Приложение","Персональные заказы и лояльность","/menu"],["Киоск","Самообслуживание без очередей","/kiosk"],["CRM","Единое управление точкой","/crm"],["Сайт","Меню и заказ онлайн","/menu"],["Кассовый терминал","Зал, оплаты и чеки","/pos"],["Склад","Остатки и списания","/crm"],["Telegram-бот","Заказ в привычном канале","/menu"],["Экран покупателя","Прозрачная корзина","/cds"],["Техкарты","Фудкост и состав","/crm"],["Карты лояльности","Бонусы в одном профиле","/menu"],["Электронная очередь","Понятная выдача","/queue"],["Отчёты и аналитика","Решения на данных","/crm"],["Доставка","Заказ до двери","/menu"],["Кухонный экран","Поток на производстве","/kds"],["Финансовый модуль","P&L и контроль денег","/crm"]];
const nav = [["menu","Меню"],["kiosk","Киоск"],["crm","CRM"],["pos","POS"],["kds","KDS"],["queue","Очередь"],["cds","CDS"]];
const money=(n:number)=>new Intl.NumberFormat("ru-RU").format(n)+" ₽";
type HomeState={orders:{total:number;status:string}[];items:unknown[];guests:unknown[]};
export default function Home() { const [s,setS]=useState<HomeState>({orders:[],items:[],guests:[]}); useEffect(()=>{fetch("/api/state").then(r=>r.json()).then(setS)},[]); const revenue=s.orders.reduce((a,o)=>a+o.total,0); return <main className="mx-auto max-w-7xl px-6 py-10">
<header className="flex items-center justify-between"><Link href="/" className="text-2xl font-bold"><span className="accent">◐</span> ЛУНА <small className="muted text-xs">DIGITAL CAFÉ</small></Link><nav className="flex flex-wrap gap-2 text-sm text-slate-300">{nav.map(([x,n])=><Link href={"/"+x} key={x}>{n}</Link>)}</nav></header>
<section className="grid gap-10 py-24 md:grid-cols-[1.15fr_.85fr] md:items-center"><div><p className="accent mb-5 uppercase tracking-[.3em]">единая экосистема кафе</p><h1 className="text-6xl font-bold leading-[.95] md:text-8xl">Кафе,<br/><span className="accent">которое</span><br/>слышит гостя.</h1><p className="muted mt-7 max-w-xl text-lg">Все каналы продаж, кухня, склад, команда и аналитика работают на одних данных.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn" href="/menu">Открыть гостевой сайт</Link></div></div><div className="panel relative overflow-hidden p-8"><p className="muted">СЕЙЧАС В СИСТЕМЕ</p><div className="mt-10 grid grid-cols-2 gap-4"><Stat n={String(s.orders.filter(o=>o.status!=="DONE").length)} t="активных заказов"/><Stat n={money(revenue)} t="выручка сегодня"/><Stat n={String(s.items.length)} t="позиций меню"/><Stat n={String(s.guests.length)} t="гостей"/></div><div className="mt-8 border-t border-[#30425a] pt-5 text-sm"><span className="accent">●</span> Синхронизация активна · polling 3 сек.</div></div></section>
<h2 className="mb-6 text-3xl font-bold">Вся платформа — в одной связке</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([n,d,u])=><Link href={u} className="panel p-5 transition hover:-translate-y-1" key={n}><div className="mb-8 text-3xl accent">✦</div><h3 className="text-lg font-bold">{n}</h3><p className="muted mt-2 text-sm">{d}</p><span className="mt-5 inline-block text-sm accent">Открыть демо →</span></Link>)}</div>
<footer className="muted mt-20 border-t border-[#233650] py-8 text-sm">Луна · демонстрационный прототип платформы автоматизации кафе</footer></main>}
function Stat({n,t}:{n:string,t:string}) { return <div><strong className="text-4xl accent">{n}</strong><p className="muted mt-1 text-sm">{t}</p></div> }
